service:
  name: AWSReviewWebsite

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  environment:
    REVIEW_TABLE_NAME: ${self:custom.ReviewTable.name}
    AUTH0_PUBLIC_KEY: ${file(secret.pem)}
    iamRoleStatements:
      - ${file(aws/iam/ReviewTableIAM.yml):ReviewTableIAM} 

resources:
  Resources:
    ReviewTable: ${file(aws/resources/ReviewTable.yml):ReviewTable}
    # This response is needed for custom authorizer failures cors support
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
functions:
  auth:
    handler: aws/handlers/auth.handler
    cors: true
  publicEndpoint:
    handler: aws/handlers/public.handler
    events:
      - http:
          path: public
          method: POST
          cors: true
  privateEndpoint:
    handler: aws/handlers/private.handler
    events:
      - http:
          path: private
          method: POST
          authorizer: auth
          cors: true
  getReviews:
    handler: aws/handlers/getReviews.handler
    events:
      - http:
          method: GET
          path: /getReviews
          authorizer: ${self:custom.authorizer}

custom:
  authorizer: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:AWSReviewWebsite-${self:provider.stage}-auth
  ReviewTable:
    name: !Ref ReviewTable
    arn: !GetAtt ReviewTable.Arn
  bundle:
    linting: true
