service:
  name: AWSReviewWebsite

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-2

# functions:
    # placeBid:
    #   handler: src/handlers/placeBid.handler
    #   events:
    #     - http:
    #         method: PATCH
    #         path: auction/{id}/bid
    #         authorizer: ${self:custom.authorizer}

custom:
  bundle:
    linting: true
