service:
  name: AWSReviewWebsite

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-2

functions:
  logSomething:
    handler: aws/handlers/logSomething.handler
    events:
      - http:
          method: GET
          path: awstest
          # authorizer: ${self:custom.authorizer}

custom:
  bundle:
    linting: true
