ReviewBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.ReviewBucket.name}

ReviewBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref ReviewBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: '*'
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.ReviewBucket.name}/*
