ReviewTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ReviewTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: slug
        AttributeType: S
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: slug
        KeyType: HASH
    # use GSI for querying on non primary key
    GlobalSecondaryIndexes:
      - IndexName: uid
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        Projection:
          ProjectionType: ALL